
services:
  - type: web
    name: living-self-mind
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: EMBED_MODEL
        value: text-embedding-3-small
      - key: FERAL_MODE
        value: "true"
